name: ucs
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch=2.5.0
  - pytorch-cuda=12.1
  - pip:
      - matplotlib==3.10.3
      - monai==1.4.0
      - numpy==1.26.4
      - opencv-python==4.11.0.86
      - pillow==11.0.0
      - pyqt5==5.15.11
      - tqdm==4.65.2
